### ISSUE TITLE
UnityConstants.SortingLayers now contains unusual values.

### ISSUE THREAD

**Issue by awardell** [nickgravelyn/UnityToolbag#10]
Since updating to Unity5 and getting "GetSortingLayerUniqueID" instead of "GetSortingLayerUserID" in SortingLayerHelper.cs, UnityConstants now generates with some unusual values for sorting layer IDs.

```C#
public static class SortingLayers
    {
        public const int Default = 0;
        public const int Tiles = 521975635;
        public const int Test = 249841643;
        public const int Entities = -1953988869;
    }
```

Is this expected behavior?

**Comment by nickgravelyn** [comment]
Honestly not sure. The API for it is private so there's naturally no documentation on it. In my (brief) testing I didn't see such erratic values, but I also didn't test a project that upgraded from 4 to 5 (I only tested in a new project).

**Comment by pharan** [comment]
Note Unity 5 now uses some kind of hash to represent layers instead of small ints.
It's expected behavior for Unity 5. If you use those, it should work.

One thing that's kinda broken in Unity 5 though is UnityToolbag's SortingLayer tools. Reflection calls need to be updated.

**Comment by nickgravelyn** [comment]
I haven't been using the tools for a while so I may not get to this soon. But feel free to submit a PR if you make a fix! :)

**Comment by ChemiKhazi** [comment]
I have a little time and I think I introduced some of the sorting layer tools, I might look into fixing this.

**Comment by ChemiKhazi** [comment]
I can't tell which version of Unity 5 introduced the SortingLayer class which deprecates a lot of the functionality in SortingLayerHelper.cs, removing the need to use reflection.

Also, Unity 5 seems to have broken sorting layers for MeshRenderers: http://answers.unity3d.com/questions/1064940/unity-5-meshrenderer-and-sortinglayer-not-working.html

**Comment by DmitriyYukhanov** [comment]
Hey, SortingLayer was introduced in 5.2.0 (http://docs.unity3d.com/ScriptReference/40_history.html)

**Comment by ChemiKhazi** [comment]
Thanks for that link @DmitriyYukhanov, I did not know that part of the docs existed.

**Comment by nickgravelyn** [comment]
Finally took a look at this and it does indeed appear to be the standard behavior. I also went and removed SortingLayerHelper in favor of SortingLayer in 499eb3152b053279f51f820272deccdf3fbc7424.
