### ISSUE TITLE
CacheBehaviour probably not increasing speed

### ISSUE THREAD

**Issue by spixy** [nickgravelyn/UnityToolbag#24]
Hi,
according to these articles
[Custom == operator, should we keep it? Unity Blog](https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/)
[Checking for null references in Unity](http://bonusdisc.com/null-references-in-unity/)
you can speed null checks in CacheBehaviour with something like this (I use this extension):

```
public static bool IsNull(this UnityEngine.Object gameObject)
{
#if UNITY_EDITOR
             return gameObject == null;
#else
             return (object) gameObject == null;
#endif
}
```

**Comment by nickgravelyn** [comment]
You're probably right, but I'm not sure it's worth putting in any trickery to speed it up. At some point my true recommendation is for scripts to simply cache fields for the things they need and then all of this is a non-issue. CacheBehaviour was a quick attempt at making this easier or getting easy wins on large code bases, but it really isn't the right way to be dealing with components in Unity, IMO.
