### ISSUE TITLE
Question: Executing the Update() behaviour

### ISSUE THREAD

**Issue by JanOschii** [nickgravelyn/UnityToolbag#25]
Hey Nick,

sorry for misusing this forum and asking here. 
I was reading a article about this library and threading:
http://blog.theknightsofunity.com/using-threads-unity/

Now I am wondering, may be it provides the solution I am searching for.

I want to be able to change the targetFrameRate instantly – without waiting for the next Update() cycle to be used. I described the problem here: https://forum.unity3d.com/threads/instantly-targetframerate-setting-from-fixedupdate.455017/

As described I believe I need to execute the Update() function earlier than defined to reset the timer.
Something similar to CancelInvoke("Update") and Invoke("Update").

I was searching in the whole interweb. 
Surprisingly It seems to me like nobody was interested in this point before. 
So I tried to find out myself and was talking a look in the call thread of a Update function:
```
Update()
0x0000000140E5253D (Unity) StackWalker::GetCurrentCallstack
0x0000000140E54231 (Unity) StackWalker::ShowCallstack
0x00000001406065B3 (Unity) GetStacktrace
0x0000000140603ABD (Unity) DebugStringToFile
0x0000000140603F1C (Unity) DebugStringToFile
0x0000000140E9239C (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000000006B2D7CB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
0x0000000006B2D6B5 (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x0000000006B2D228 (Mono JIT Code) [Logger.cs:42] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x0000000006B2CB5C (Mono JIT Code) [UnityEngineDebugBindings.gen.cs:101] UnityEngine.Debug:Log (object) 
0x0000000006B2C37F (Mono JIT Code) [SetFPS.cs:89] SetFPS:Update () 
0x0000000005D16B42 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x000007FEDC1E539F (mono) [mini.c:4937] mono_jit_runtime_invoke 
0x000007FEDC138385 (mono) [object.c:2623] mono_runtime_invoke 
0x00000001404CD59B (Unity) ScriptingInvocationNoArgs::Invoke
0x00000001404CD527 (Unity) ScriptingInvocationNoArgs::Invoke
0x0000000140344461 (Unity) MonoBehaviour::CallMethodIfAvailable
0x00000001403480E2 (Unity) MonoBehaviour::CallUpdateMethod
0x000000014013065A (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x00000001401309D9 (Unity) BehaviourManager::Update
0x000000014046AF17 (Unity) PlayerLoop
0x0000000140BE0A95 (Unity) Application::UpdateScene
0x0000000140BE2019 (Unity) Application::UpdateSceneIfNeeded
0x0000000140BE9EB4 (Unity) Application::TickTimer
0x0000000140E4CC6E (Unity) FindMonoBinaryToUse
0x0000000140E4E2A1 (Unity) WinMain
0x00000001415B2F10 (Unity) strnlen
0x0000000077A759CD (kernel32) BaseThreadInitThunk
```

Here we see the BaseThread, a TickTimer, a UpdateScene function and MonoBehavior.CallUpdateMethod().
I tried to get access to this functions, but failed.

Do you know, how to call this stack from a script?
Could it be realized with your library?
Do you have a idea, where I should search to find a answer?

Thanks a lot

Jan

PS: Sorry for bothering, but I am a bit stranded.

**Comment by nickgravelyn** [comment]
I'm not really sure about the targetFrameRate but the Unity forums are the best place to ask.

**Comment by wolfreak99** [comment]
@JanOschii do me a favor and email me, jbminor1991 at gmail, and i can see if i can help you there. i don't want to help you through here because, as we all know this isn't really an appropriate area lol.
